# Generated by Django 3.0.6 on 2020-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='deck',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
