# Generated by Django 3.0.6 on 2020-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_word_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='deck',
            field=models.CharField(max_length=20),
        ),
    ]
