# Generated by Django 3.1.1 on 2020-10-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201001_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word'},
        ),
    ]
