# Generated by Django 3.1.1 on 2020-10-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201001_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name': 'Deck name'},
        ),
        migrations.AlterField(
            model_name='word',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.pack'),
        ),
    ]
