# Generated by Django 3.1.1 on 2020-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20201007_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='word',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
