# Generated by Django 3.1.1 on 2020-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_word_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
