# Generated by Django 3.1.1 on 2020-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20201010_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='visible',
            field=models.BooleanField(blank=True),
        ),
    ]
